### PR TITLE
Sample TextSwitcher implemented

### PR DESCRIPTION
**Pull request by gonzalonm**
Implementation of android sample TextSwitcher

### CODE REVIEW

**Comment by pjcollins** [comment]
Hey @gonzalonm - one immediate piece of feedback (which I should have mentioned earlier) is that we have the `Logger` related functionality already implemented in a library here:

* https://github.com/xamarin/monodroid-samples/tree/master/CommonSampleLibrary

Would you mind amending your PR to reference this project instead of including the `Logger` files?

Here's an example which uses CommonSampleLibrary as a project reference:
* https://github.com/xamarin/monodroid-samples/tree/master/BatchStepSensor

**Comment by gonzalonm** [comment]
Yes, I wanted to do that! Ok, no problem, I'll update the PR adding the reference to that library.

**Comment by gonzalonm** [comment]
@pjcollins referenced project added. Let me know if I forgot to add something

**Comment by pjcollins** [comment]
Merged in #250

**Pull request closed without merging**
