### PR TITLE
facebook sample using Xamarin.Facebook public NuGet

### PR DESCRIPTION
**Pull request by gonzalonm**
Update sample from https://github.com/facebook/facebook-android-sdk/tree/master/samples/HelloFacebookSample

### CODE REVIEW

**Comment by gonzalonm** [comment]
Bug: https://bugzilla.xamarin.com/show_bug.cgi?id=42893

**Comment by olegoid** [comment]
Hello @gonzalonm, a couple of changes would be great to add:
* Remove `Xamarin.Facebook` project from solution file
* Remove `../Facebook/samples/simple/simple/Example.cs`

Actually I can't see `Xamarin.Facebook` NuGet reference in `HelloFacebookSample` project(there is a reference to the `Xamarin.Facebook` project but this project should be removed and replaced with respective nuget).

**Comment by gonzalonm** [comment]
Don't know what happened. I had to add again Xamarin.Facebook NuGet package and I had to remove Xamarin.Project again from the solution. Now, it should be updated.

**Comment by olegoid** [comment]
LGTM now

**Pull request merged**
