### PR TITLE
Create direct reply

### PR DESCRIPTION
**Pull request by gonzalonm**

### CODE REVIEW

**Comment by olegoid** [comment]
@gonzalonm please add the following assets:
* Sample readme
* metadata file
* Screenshots folder(with at least one screenshot)

You can learn more about how to create above resource [here](https://github.com/xamarin/monodroid-samples/blob/master/README.md#sample-requirements).

Currently, we're moving from mono coding to style to traditional VS style. So I can't really say for sure how the code should be formatted ;)

However, you got to decide what do you prefer:
* tabs vs spaces(now I can see both tabs and spaces)
* to put space between method name and opening brace or not
* etc.
and try to keep this style in the whole project.

Historically our repository has used a mix of coding styles. So if you're working with legacy code try to follow the style already used in the project. The main idea is to have one style per project.

**Comment by jamesmontemagno** [comment]
;)

**Comment by gonzalonm** [comment]
Added required assets. Applied a code format using by Xamarin Studio for .cs files. Let me know if I forgot format any files

**Comment by olegoid** [comment]
@gonzalonm could you move this sample to `android-n` directory? I think messages service was not available in earlier versions of android.

Beside that I think we're pretty good to merge.

**Comment by gonzalonm** [comment]
Project moved to `android-n` folder

**Pull request merged**
